var wms_layers = [];


        var lyr_GoogleSatelliteHybrid_0 = new ol.layer.Tile({
            'title': 'Google Satellite Hybrid',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
            attributions: ' ',
                url: 'https://mt0.google.com/vt/lyrs=y&x={x}&y={y}&z={z}'
            })
        });
var format_Kommunegrnse_slagelsekommuneinddeling_dagi_110000_1 = new ol.format.GeoJSON();
var features_Kommunegrnse_slagelsekommuneinddeling_dagi_110000_1 = format_Kommunegrnse_slagelsekommuneinddeling_dagi_110000_1.readFeatures(json_Kommunegrnse_slagelsekommuneinddeling_dagi_110000_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Kommunegrnse_slagelsekommuneinddeling_dagi_110000_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Kommunegrnse_slagelsekommuneinddeling_dagi_110000_1.addFeatures(features_Kommunegrnse_slagelsekommuneinddeling_dagi_110000_1);
var lyr_Kommunegrnse_slagelsekommuneinddeling_dagi_110000_1 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Kommunegrnse_slagelsekommuneinddeling_dagi_110000_1, 
                style: style_Kommunegrnse_slagelsekommuneinddeling_dagi_110000_1,
                popuplayertitle: 'Kommunegrænse_slagelse — kommuneinddeling_dagi_110000',
                interactive: false,
                title: '<img src="styles/legend/Kommunegrnse_slagelsekommuneinddeling_dagi_110000_1.png" /> Kommunegrænse_slagelse — kommuneinddeling_dagi_110000'
            });
var format_25mhjdekurveeksportdhm_kurve__25_m_wfs_2 = new ol.format.GeoJSON();
var features_25mhjdekurveeksportdhm_kurve__25_m_wfs_2 = format_25mhjdekurveeksportdhm_kurve__25_m_wfs_2.readFeatures(json_25mhjdekurveeksportdhm_kurve__25_m_wfs_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_25mhjdekurveeksportdhm_kurve__25_m_wfs_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_25mhjdekurveeksportdhm_kurve__25_m_wfs_2.addFeatures(features_25mhjdekurveeksportdhm_kurve__25_m_wfs_2);
var lyr_25mhjdekurveeksportdhm_kurve__25_m_wfs_2 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_25mhjdekurveeksportdhm_kurve__25_m_wfs_2, 
                style: style_25mhjdekurveeksportdhm_kurve__25_m_wfs_2,
                popuplayertitle: '2.5m højdekurve eksport — dhm_kurve__25_m_wfs',
                interactive: false,
                title: '<img src="styles/legend/25mhjdekurveeksportdhm_kurve__25_m_wfs_2.png" /> 2.5m højdekurve eksport — dhm_kurve__25_m_wfs'
            });
var format_Vandlbsmidte_slagelse_sydvandlbsmidte_3 = new ol.format.GeoJSON();
var features_Vandlbsmidte_slagelse_sydvandlbsmidte_3 = format_Vandlbsmidte_slagelse_sydvandlbsmidte_3.readFeatures(json_Vandlbsmidte_slagelse_sydvandlbsmidte_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Vandlbsmidte_slagelse_sydvandlbsmidte_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Vandlbsmidte_slagelse_sydvandlbsmidte_3.addFeatures(features_Vandlbsmidte_slagelse_sydvandlbsmidte_3);
var lyr_Vandlbsmidte_slagelse_sydvandlbsmidte_3 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Vandlbsmidte_slagelse_sydvandlbsmidte_3,
maxResolution:28004.466152261964,
 
                style: style_Vandlbsmidte_slagelse_sydvandlbsmidte_3,
                popuplayertitle: 'Vandløbsmidte_slagelse_syd — vandlbsmidte',
                interactive: false,
                title: '<img src="styles/legend/Vandlbsmidte_slagelse_sydvandlbsmidte_3.png" /> Vandløbsmidte_slagelse_syd — vandlbsmidte'
            });
var format_Jordstykker_matrikler_slagelse_v4jordstykke_gldende_4 = new ol.format.GeoJSON();
var features_Jordstykker_matrikler_slagelse_v4jordstykke_gldende_4 = format_Jordstykker_matrikler_slagelse_v4jordstykke_gldende_4.readFeatures(json_Jordstykker_matrikler_slagelse_v4jordstykke_gldende_4, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Jordstykker_matrikler_slagelse_v4jordstykke_gldende_4 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Jordstykker_matrikler_slagelse_v4jordstykke_gldende_4.addFeatures(features_Jordstykker_matrikler_slagelse_v4jordstykke_gldende_4);
var lyr_Jordstykker_matrikler_slagelse_v4jordstykke_gldende_4 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Jordstykker_matrikler_slagelse_v4jordstykke_gldende_4, 
                style: style_Jordstykker_matrikler_slagelse_v4jordstykke_gldende_4,
                popuplayertitle: 'Jordstykker_matrikler_slagelse_v4 — jordstykke_gldende',
                interactive: false,
                title: '<img src="styles/legend/Jordstykker_matrikler_slagelse_v4jordstykke_gldende_4.png" /> Jordstykker_matrikler_slagelse_v4 — jordstykke_gldende'
            });
var format_Jordstykker_matrikler_slagelse_v3jordstykke_gldende_5 = new ol.format.GeoJSON();
var features_Jordstykker_matrikler_slagelse_v3jordstykke_gldende_5 = format_Jordstykker_matrikler_slagelse_v3jordstykke_gldende_5.readFeatures(json_Jordstykker_matrikler_slagelse_v3jordstykke_gldende_5, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Jordstykker_matrikler_slagelse_v3jordstykke_gldende_5 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Jordstykker_matrikler_slagelse_v3jordstykke_gldende_5.addFeatures(features_Jordstykker_matrikler_slagelse_v3jordstykke_gldende_5);
var lyr_Jordstykker_matrikler_slagelse_v3jordstykke_gldende_5 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Jordstykker_matrikler_slagelse_v3jordstykke_gldende_5, 
                style: style_Jordstykker_matrikler_slagelse_v3jordstykke_gldende_5,
                popuplayertitle: 'Jordstykker_matrikler_slagelse_v3 — jordstykke_gldende',
                interactive: false,
                title: '<img src="styles/legend/Jordstykker_matrikler_slagelse_v3jordstykke_gldende_5.png" /> Jordstykker_matrikler_slagelse_v3 — jordstykke_gldende'
            });
var format_Jordstykker_matrikler_slagelse_v2jordstykke_gldende_6 = new ol.format.GeoJSON();
var features_Jordstykker_matrikler_slagelse_v2jordstykke_gldende_6 = format_Jordstykker_matrikler_slagelse_v2jordstykke_gldende_6.readFeatures(json_Jordstykker_matrikler_slagelse_v2jordstykke_gldende_6, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Jordstykker_matrikler_slagelse_v2jordstykke_gldende_6 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Jordstykker_matrikler_slagelse_v2jordstykke_gldende_6.addFeatures(features_Jordstykker_matrikler_slagelse_v2jordstykke_gldende_6);
var lyr_Jordstykker_matrikler_slagelse_v2jordstykke_gldende_6 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Jordstykker_matrikler_slagelse_v2jordstykke_gldende_6, 
                style: style_Jordstykker_matrikler_slagelse_v2jordstykke_gldende_6,
                popuplayertitle: 'Jordstykker_matrikler_slagelse_v2 — jordstykke_gldende',
                interactive: false,
                title: '<img src="styles/legend/Jordstykker_matrikler_slagelse_v2jordstykke_gldende_6.png" /> Jordstykker_matrikler_slagelse_v2 — jordstykke_gldende'
            });
var format_Jordstykker_matrikler_slagelsejordstykke_gldende_7 = new ol.format.GeoJSON();
var features_Jordstykker_matrikler_slagelsejordstykke_gldende_7 = format_Jordstykker_matrikler_slagelsejordstykke_gldende_7.readFeatures(json_Jordstykker_matrikler_slagelsejordstykke_gldende_7, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Jordstykker_matrikler_slagelsejordstykke_gldende_7 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Jordstykker_matrikler_slagelsejordstykke_gldende_7.addFeatures(features_Jordstykker_matrikler_slagelsejordstykke_gldende_7);
var lyr_Jordstykker_matrikler_slagelsejordstykke_gldende_7 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Jordstykker_matrikler_slagelsejordstykke_gldende_7, 
                style: style_Jordstykker_matrikler_slagelsejordstykke_gldende_7,
                popuplayertitle: 'Jordstykker_matrikler_slagelse — jordstykke_gldende',
                interactive: false,
                title: '<img src="styles/legend/Jordstykker_matrikler_slagelsejordstykke_gldende_7.png" /> Jordstykker_matrikler_slagelse — jordstykke_gldende'
            });
var format_Kortlgges_feltID_8 = new ol.format.GeoJSON();
var features_Kortlgges_feltID_8 = format_Kortlgges_feltID_8.readFeatures(json_Kortlgges_feltID_8, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Kortlgges_feltID_8 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Kortlgges_feltID_8.addFeatures(features_Kortlgges_feltID_8);
var lyr_Kortlgges_feltID_8 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Kortlgges_feltID_8, 
                style: style_Kortlgges_feltID_8,
                popuplayertitle: 'Kortlægges_feltID',
                interactive: true,
    title: 'Kortlægges_feltID<br />\
    <img src="styles/legend/Kortlgges_feltID_8_0.png" /> Hede<br />\
    <img src="styles/legend/Kortlgges_feltID_8_1.png" /> Mose<br />\
    <img src="styles/legend/Kortlgges_feltID_8_2.png" /> Strandeng<br />\
    <img src="styles/legend/Kortlgges_feltID_8_3.png" /> Eng<br />\
    <img src="styles/legend/Kortlgges_feltID_8_4.png" /> Overdrev<br />' });
var group_Matrikler = new ol.layer.Group({
                                layers: [lyr_Jordstykker_matrikler_slagelse_v4jordstykke_gldende_4,lyr_Jordstykker_matrikler_slagelse_v3jordstykke_gldende_5,lyr_Jordstykker_matrikler_slagelse_v2jordstykke_gldende_6,lyr_Jordstykker_matrikler_slagelsejordstykke_gldende_7,],
                                fold: 'close',
                                title: 'Matrikler'});

lyr_GoogleSatelliteHybrid_0.setVisible(true);lyr_Kommunegrnse_slagelsekommuneinddeling_dagi_110000_1.setVisible(true);lyr_25mhjdekurveeksportdhm_kurve__25_m_wfs_2.setVisible(true);lyr_Vandlbsmidte_slagelse_sydvandlbsmidte_3.setVisible(true);lyr_Jordstykker_matrikler_slagelse_v4jordstykke_gldende_4.setVisible(true);lyr_Jordstykker_matrikler_slagelse_v3jordstykke_gldende_5.setVisible(true);lyr_Jordstykker_matrikler_slagelse_v2jordstykke_gldende_6.setVisible(true);lyr_Jordstykker_matrikler_slagelsejordstykke_gldende_7.setVisible(true);lyr_Kortlgges_feltID_8.setVisible(true);
var layersList = [lyr_GoogleSatelliteHybrid_0,lyr_Kommunegrnse_slagelsekommuneinddeling_dagi_110000_1,lyr_25mhjdekurveeksportdhm_kurve__25_m_wfs_2,lyr_Vandlbsmidte_slagelse_sydvandlbsmidte_3,group_Matrikler,lyr_Kortlgges_feltID_8];
lyr_Kommunegrnse_slagelsekommuneinddeling_dagi_110000_1.set('fieldAliases', {'fid': 'fid', 'id': 'id', 'metadataproperty': 'metadataproperty', 'description_href': 'description_href', 'description_title': 'description_title', 'description_nilreason': 'description_nilreason', 'description': 'description', 'descriptionreference_href': 'descriptionreference_href', 'descriptionreference_title': 'descriptionreference_title', 'descriptionreference_nilreason': 'descriptionreference_nilreason', 'identifier_codespace': 'identifier_codespace', 'identifier': 'identifier', 'name': 'name', 'location_location': 'location_location', 'id.namespace': 'id.namespace', 'id.lokalid': 'id.lokalid', 'status': 'status', 'geometristatus': 'geometristatus', 'virkningfra': 'virkningfra', 'virkningtil': 'virkningtil', 'virkningsaktoer': 'virkningsaktoer', 'forretningshaendelse': 'forretningshaendelse', 'registreringfra': 'registreringfra', 'registreringtil': 'registreringtil', 'registreringsaktoer': 'registreringsaktoer', 'forretningsomraade': 'forretningsomraade', 'forretningsproces': 'forretningsproces', 'dagiid': 'dagiid', 'navn': 'navn', 'redigeringsret': 'redigeringsret', 'dataspecifikation': 'dataspecifikation', 'landekode': 'landekode', 'skala': 'skala', 'udtraeksdato': 'udtraeksdato', 'kommunekode': 'kommunekode', 'lau1vaerdi': 'lau1vaerdi', 'udenforkommuneinddeling': 'udenforkommuneinddeling', 'regionskode': 'regionskode', 'regionslokalid': 'regionslokalid', 'region_owns': 'region_owns', 'region_href': 'region_href', 'region_title': 'region_title', 'region_nilreason': 'region_nilreason', });
lyr_25mhjdekurveeksportdhm_kurve__25_m_wfs_2.set('fieldAliases', {'fid': 'fid', 'kurveId': 'kurveId', 'objektnavn': 'objektnavn', 'hjaelpekurve': 'hjaelpekurve', 'hoejde': 'hoejde', });
lyr_Vandlbsmidte_slagelse_sydvandlbsmidte_3.set('fieldAliases', {'fid': 'fid', 'id': 'id', 'metadataproperty': 'metadataproperty', 'description_href': 'description_href', 'description_title': 'description_title', 'description_nilreason': 'description_nilreason', 'description': 'description', 'descriptionreference_href': 'descriptionreference_href', 'descriptionreference_title': 'descriptionreference_title', 'descriptionreference_nilreason': 'descriptionreference_nilreason', 'identifier_codespace': 'identifier_codespace', 'identifier': 'identifier', 'name': 'name', 'location_location': 'location_location', 'id.namespace': 'id.namespace', 'id.lokalid': 'id.lokalid', 'tempid': 'tempid', 'status': 'status', 'geometristatus': 'geometristatus', 'registreringsspecifikation': 'registreringsspecifikation', 'dataansvar': 'dataansvar', 'forretningshaendelse': 'forretningshaendelse', 'forretningsomraade': 'forretningsomraade', 'forretningsproces': 'forretningsproces', 'registreringsaktoer': 'registreringsaktoer', 'registreringfra': 'registreringfra', 'registreringtil': 'registreringtil', 'virkningsaktoer': 'virkningsaktoer', 'virkningfra': 'virkningfra', 'virkningtil': 'virkningtil', 'plannoejagtighed': 'plannoejagtighed', 'planstedfaestelsesmetode': 'planstedfaestelsesmetode', 'vertikalnoejagtighed': 'vertikalnoejagtighed', 'vertikalstedfaestelsesmetode': 'vertikalstedfaestelsesmetode', 'applikation': 'applikation', 'kommentar': 'kommentar', 'vandloebstype': 'vandloebstype', 'vanduuid': 'vanduuid', 'fraknude': 'fraknude', 'tilknude': 'tilknude', 'faldretning': 'faldretning', 'netvaerk': 'netvaerk', 'midtebredde': 'midtebredde', 'synligvandloebsmidte': 'synligvandloebsmidte', 'link': 'link', });
lyr_Jordstykker_matrikler_slagelse_v4jordstykke_gldende_4.set('fieldAliases', {'fid': 'fid', 'id': 'id', 'metadataproperty': 'metadataproperty', 'description_href': 'description_href', 'description_title': 'description_title', 'description_nilreason': 'description_nilreason', 'description': 'description', 'descriptionreference_href': 'descriptionreference_href', 'descriptionreference_title': 'descriptionreference_title', 'descriptionreference_nilreason': 'descriptionreference_nilreason', 'identifier_codespace': 'identifier_codespace', 'identifier': 'identifier', 'name': 'name', 'location_location': 'location_location', 'forretningshaendelse': 'forretningshaendelse', 'senestesaglokalid': 'senestesaglokalid', 'forretningsproces': 'forretningsproces', 'id.namespace': 'id.namespace', 'id.lokalid': 'id.lokalid', 'paataenkthandling': 'paataenkthandling', 'registreringfra': 'registreringfra', 'virkningfra': 'virkningfra', 'virkningsaktoer': 'virkningsaktoer', 'samletfastejendomlokalid': 'samletfastejendomlokalid', 'skelforretningssagslokalid': 'skelforretningssagslokalid', 'stammerfrajordstykkelokalid': 'stammerfrajordstykkelokalid', 'supplerendemaalingsaglokalid': 'supplerendemaalingsaglokalid', 'arealberegningsmetode': 'arealberegningsmetode', 'arealbetegnelse': 'arealbetegnelse', 'arealtype': 'arealtype', 'brugsretsareal': 'brugsretsareal', 'delnummer': 'delnummer', 'faelleslod': 'faelleslod', 'matrikelnummer': 'matrikelnummer', 'ejerlavskode': 'ejerlavskode', 'sognekode': 'sognekode', 'kommunekode': 'kommunekode', 'regionskode': 'regionskode', 'registreretareal_uom': 'registreretareal_uom', 'registreretareal': 'registreretareal', 'vandarealinkludering': 'vandarealinkludering', 'vejareal_uom': 'vejareal_uom', 'vejareal': 'vejareal', 'vejarealberegningsstatus': 'vejarealberegningsstatus', 'fredskov.areal_uom': 'fredskov.areal_uom', 'fredskov.areal': 'fredskov.areal', 'fredskov.omfang': 'fredskov.omfang', 'jordrente.omfang': 'jordrente.omfang', 'klitfredning.areal_uom': 'klitfredning.areal_uom', 'klitfredning.areal': 'klitfredning.areal', 'klitfredning.omfang': 'klitfredning.omfang', 'majoratsskov.nummer': 'majoratsskov.nummer', 'majoratsskov.omfang': 'majoratsskov.omfang', 'strandbeskyttelse.omfang': 'strandbeskyttelse.omfang', 'strandbeskyttelse.areal_uom': 'strandbeskyttelse.areal_uom', 'strandbeskyttelse.areal': 'strandbeskyttelse.areal', 'stormfaldsnotering': 'stormfaldsnotering', });
lyr_Jordstykker_matrikler_slagelse_v3jordstykke_gldende_5.set('fieldAliases', {'fid': 'fid', 'id': 'id', 'metadataproperty': 'metadataproperty', 'description_href': 'description_href', 'description_title': 'description_title', 'description_nilreason': 'description_nilreason', 'description': 'description', 'descriptionreference_href': 'descriptionreference_href', 'descriptionreference_title': 'descriptionreference_title', 'descriptionreference_nilreason': 'descriptionreference_nilreason', 'identifier_codespace': 'identifier_codespace', 'identifier': 'identifier', 'name': 'name', 'location_location': 'location_location', 'forretningshaendelse': 'forretningshaendelse', 'senestesaglokalid': 'senestesaglokalid', 'forretningsproces': 'forretningsproces', 'id.namespace': 'id.namespace', 'id.lokalid': 'id.lokalid', 'paataenkthandling': 'paataenkthandling', 'registreringfra': 'registreringfra', 'virkningfra': 'virkningfra', 'virkningsaktoer': 'virkningsaktoer', 'samletfastejendomlokalid': 'samletfastejendomlokalid', 'skelforretningssagslokalid': 'skelforretningssagslokalid', 'stammerfrajordstykkelokalid': 'stammerfrajordstykkelokalid', 'supplerendemaalingsaglokalid': 'supplerendemaalingsaglokalid', 'arealberegningsmetode': 'arealberegningsmetode', 'arealbetegnelse': 'arealbetegnelse', 'arealtype': 'arealtype', 'brugsretsareal': 'brugsretsareal', 'delnummer': 'delnummer', 'faelleslod': 'faelleslod', 'matrikelnummer': 'matrikelnummer', 'ejerlavskode': 'ejerlavskode', 'sognekode': 'sognekode', 'kommunekode': 'kommunekode', 'regionskode': 'regionskode', 'registreretareal_uom': 'registreretareal_uom', 'registreretareal': 'registreretareal', 'vandarealinkludering': 'vandarealinkludering', 'vejareal_uom': 'vejareal_uom', 'vejareal': 'vejareal', 'vejarealberegningsstatus': 'vejarealberegningsstatus', 'fredskov.areal_uom': 'fredskov.areal_uom', 'fredskov.areal': 'fredskov.areal', 'fredskov.omfang': 'fredskov.omfang', 'jordrente.omfang': 'jordrente.omfang', 'klitfredning.areal_uom': 'klitfredning.areal_uom', 'klitfredning.areal': 'klitfredning.areal', 'klitfredning.omfang': 'klitfredning.omfang', 'majoratsskov.nummer': 'majoratsskov.nummer', 'majoratsskov.omfang': 'majoratsskov.omfang', 'strandbeskyttelse.omfang': 'strandbeskyttelse.omfang', 'strandbeskyttelse.areal_uom': 'strandbeskyttelse.areal_uom', 'strandbeskyttelse.areal': 'strandbeskyttelse.areal', 'stormfaldsnotering': 'stormfaldsnotering', });
lyr_Jordstykker_matrikler_slagelse_v2jordstykke_gldende_6.set('fieldAliases', {'fid': 'fid', 'id': 'id', 'metadataproperty': 'metadataproperty', 'description_href': 'description_href', 'description_title': 'description_title', 'description_nilreason': 'description_nilreason', 'description': 'description', 'descriptionreference_href': 'descriptionreference_href', 'descriptionreference_title': 'descriptionreference_title', 'descriptionreference_nilreason': 'descriptionreference_nilreason', 'identifier_codespace': 'identifier_codespace', 'identifier': 'identifier', 'name': 'name', 'location_location': 'location_location', 'forretningshaendelse': 'forretningshaendelse', 'senestesaglokalid': 'senestesaglokalid', 'forretningsproces': 'forretningsproces', 'id.namespace': 'id.namespace', 'id.lokalid': 'id.lokalid', 'paataenkthandling': 'paataenkthandling', 'registreringfra': 'registreringfra', 'virkningfra': 'virkningfra', 'virkningsaktoer': 'virkningsaktoer', 'samletfastejendomlokalid': 'samletfastejendomlokalid', 'skelforretningssagslokalid': 'skelforretningssagslokalid', 'stammerfrajordstykkelokalid': 'stammerfrajordstykkelokalid', 'supplerendemaalingsaglokalid': 'supplerendemaalingsaglokalid', 'arealberegningsmetode': 'arealberegningsmetode', 'arealbetegnelse': 'arealbetegnelse', 'arealtype': 'arealtype', 'brugsretsareal': 'brugsretsareal', 'delnummer': 'delnummer', 'faelleslod': 'faelleslod', 'matrikelnummer': 'matrikelnummer', 'ejerlavskode': 'ejerlavskode', 'sognekode': 'sognekode', 'kommunekode': 'kommunekode', 'regionskode': 'regionskode', 'registreretareal_uom': 'registreretareal_uom', 'registreretareal': 'registreretareal', 'vandarealinkludering': 'vandarealinkludering', 'vejareal_uom': 'vejareal_uom', 'vejareal': 'vejareal', 'vejarealberegningsstatus': 'vejarealberegningsstatus', 'fredskov.areal_uom': 'fredskov.areal_uom', 'fredskov.areal': 'fredskov.areal', 'fredskov.omfang': 'fredskov.omfang', 'jordrente.omfang': 'jordrente.omfang', 'klitfredning.areal_uom': 'klitfredning.areal_uom', 'klitfredning.areal': 'klitfredning.areal', 'klitfredning.omfang': 'klitfredning.omfang', 'majoratsskov.nummer': 'majoratsskov.nummer', 'majoratsskov.omfang': 'majoratsskov.omfang', 'strandbeskyttelse.omfang': 'strandbeskyttelse.omfang', 'strandbeskyttelse.areal_uom': 'strandbeskyttelse.areal_uom', 'strandbeskyttelse.areal': 'strandbeskyttelse.areal', 'stormfaldsnotering': 'stormfaldsnotering', });
lyr_Jordstykker_matrikler_slagelsejordstykke_gldende_7.set('fieldAliases', {'fid': 'fid', 'id': 'id', 'metadataproperty': 'metadataproperty', 'description_href': 'description_href', 'description_title': 'description_title', 'description_nilreason': 'description_nilreason', 'description': 'description', 'descriptionreference_href': 'descriptionreference_href', 'descriptionreference_title': 'descriptionreference_title', 'descriptionreference_nilreason': 'descriptionreference_nilreason', 'identifier_codespace': 'identifier_codespace', 'identifier': 'identifier', 'name': 'name', 'location_location': 'location_location', 'forretningshaendelse': 'forretningshaendelse', 'senestesaglokalid': 'senestesaglokalid', 'forretningsproces': 'forretningsproces', 'id.namespace': 'id.namespace', 'id.lokalid': 'id.lokalid', 'paataenkthandling': 'paataenkthandling', 'registreringfra': 'registreringfra', 'virkningfra': 'virkningfra', 'virkningsaktoer': 'virkningsaktoer', 'samletfastejendomlokalid': 'samletfastejendomlokalid', 'skelforretningssagslokalid': 'skelforretningssagslokalid', 'stammerfrajordstykkelokalid': 'stammerfrajordstykkelokalid', 'supplerendemaalingsaglokalid': 'supplerendemaalingsaglokalid', 'arealberegningsmetode': 'arealberegningsmetode', 'arealbetegnelse': 'arealbetegnelse', 'arealtype': 'arealtype', 'brugsretsareal': 'brugsretsareal', 'delnummer': 'delnummer', 'faelleslod': 'faelleslod', 'matrikelnummer': 'matrikelnummer', 'ejerlavskode': 'ejerlavskode', 'sognekode': 'sognekode', 'kommunekode': 'kommunekode', 'regionskode': 'regionskode', 'registreretareal_uom': 'registreretareal_uom', 'registreretareal': 'registreretareal', 'vandarealinkludering': 'vandarealinkludering', 'vejareal_uom': 'vejareal_uom', 'vejareal': 'vejareal', 'vejarealberegningsstatus': 'vejarealberegningsstatus', 'fredskov.areal_uom': 'fredskov.areal_uom', 'fredskov.areal': 'fredskov.areal', 'fredskov.omfang': 'fredskov.omfang', 'jordrente.omfang': 'jordrente.omfang', 'klitfredning.areal_uom': 'klitfredning.areal_uom', 'klitfredning.areal': 'klitfredning.areal', 'klitfredning.omfang': 'klitfredning.omfang', 'majoratsskov.nummer': 'majoratsskov.nummer', 'majoratsskov.omfang': 'majoratsskov.omfang', 'strandbeskyttelse.omfang': 'strandbeskyttelse.omfang', 'strandbeskyttelse.areal_uom': 'strandbeskyttelse.areal_uom', 'strandbeskyttelse.areal': 'strandbeskyttelse.areal', 'stormfaldsnotering': 'stormfaldsnotering', });
lyr_Kortlgges_feltID_8.set('fieldAliases', {'Objekt_id': 'DMP objekt_ID', 'Natyp_navn': 'Naturtype', 'StedNavn': 'Slagelse ID', 'Orden': 'Afstand fra ref.punkt', 'Polygon_name': 'FeltID', });
lyr_Kommunegrnse_slagelsekommuneinddeling_dagi_110000_1.set('fieldImages', {'fid': 'TextEdit', 'id': 'TextEdit', 'metadataproperty': 'TextEdit', 'description_href': 'TextEdit', 'description_title': 'TextEdit', 'description_nilreason': 'TextEdit', 'description': 'TextEdit', 'descriptionreference_href': 'TextEdit', 'descriptionreference_title': 'TextEdit', 'descriptionreference_nilreason': 'TextEdit', 'identifier_codespace': 'TextEdit', 'identifier': 'TextEdit', 'name': 'TextEdit', 'location_location': 'TextEdit', 'id.namespace': 'TextEdit', 'id.lokalid': 'TextEdit', 'status': 'TextEdit', 'geometristatus': 'TextEdit', 'virkningfra': 'DateTime', 'virkningtil': 'DateTime', 'virkningsaktoer': 'TextEdit', 'forretningshaendelse': 'TextEdit', 'registreringfra': 'DateTime', 'registreringtil': 'DateTime', 'registreringsaktoer': 'TextEdit', 'forretningsomraade': 'TextEdit', 'forretningsproces': 'TextEdit', 'dagiid': 'TextEdit', 'navn': 'TextEdit', 'redigeringsret': 'TextEdit', 'dataspecifikation': 'TextEdit', 'landekode': 'TextEdit', 'skala': 'TextEdit', 'udtraeksdato': 'DateTime', 'kommunekode': 'TextEdit', 'lau1vaerdi': 'TextEdit', 'udenforkommuneinddeling': 'CheckBox', 'regionskode': 'TextEdit', 'regionslokalid': 'TextEdit', 'region_owns': 'CheckBox', 'region_href': 'TextEdit', 'region_title': 'TextEdit', 'region_nilreason': 'TextEdit', });
lyr_25mhjdekurveeksportdhm_kurve__25_m_wfs_2.set('fieldImages', {'fid': 'TextEdit', 'kurveId': 'TextEdit', 'objektnavn': 'TextEdit', 'hjaelpekurve': 'CheckBox', 'hoejde': 'TextEdit', });
lyr_Vandlbsmidte_slagelse_sydvandlbsmidte_3.set('fieldImages', {'fid': 'TextEdit', 'id': 'TextEdit', 'metadataproperty': 'TextEdit', 'description_href': 'TextEdit', 'description_title': 'TextEdit', 'description_nilreason': 'TextEdit', 'description': 'TextEdit', 'descriptionreference_href': 'TextEdit', 'descriptionreference_title': 'TextEdit', 'descriptionreference_nilreason': 'TextEdit', 'identifier_codespace': 'TextEdit', 'identifier': 'TextEdit', 'name': 'TextEdit', 'location_location': 'TextEdit', 'id.namespace': 'TextEdit', 'id.lokalid': 'TextEdit', 'tempid': 'TextEdit', 'status': 'TextEdit', 'geometristatus': 'TextEdit', 'registreringsspecifikation': 'TextEdit', 'dataansvar': 'TextEdit', 'forretningshaendelse': 'TextEdit', 'forretningsomraade': 'TextEdit', 'forretningsproces': 'TextEdit', 'registreringsaktoer': 'TextEdit', 'registreringfra': 'DateTime', 'registreringtil': 'DateTime', 'virkningsaktoer': 'TextEdit', 'virkningfra': 'DateTime', 'virkningtil': 'DateTime', 'plannoejagtighed': 'TextEdit', 'planstedfaestelsesmetode': 'TextEdit', 'vertikalnoejagtighed': 'TextEdit', 'vertikalstedfaestelsesmetode': 'TextEdit', 'applikation': 'TextEdit', 'kommentar': 'TextEdit', 'vandloebstype': 'TextEdit', 'vanduuid': 'TextEdit', 'fraknude': 'TextEdit', 'tilknude': 'TextEdit', 'faldretning': 'TextEdit', 'netvaerk': 'CheckBox', 'midtebredde': 'TextEdit', 'synligvandloebsmidte': 'CheckBox', 'link': 'TextEdit', });
lyr_Jordstykker_matrikler_slagelse_v4jordstykke_gldende_4.set('fieldImages', {'fid': 'TextEdit', 'id': 'TextEdit', 'metadataproperty': 'TextEdit', 'description_href': 'TextEdit', 'description_title': 'TextEdit', 'description_nilreason': 'TextEdit', 'description': 'TextEdit', 'descriptionreference_href': 'TextEdit', 'descriptionreference_title': 'TextEdit', 'descriptionreference_nilreason': 'TextEdit', 'identifier_codespace': 'TextEdit', 'identifier': 'TextEdit', 'name': 'TextEdit', 'location_location': 'TextEdit', 'forretningshaendelse': 'TextEdit', 'senestesaglokalid': 'TextEdit', 'forretningsproces': 'TextEdit', 'id.namespace': 'TextEdit', 'id.lokalid': 'TextEdit', 'paataenkthandling': 'TextEdit', 'registreringfra': 'DateTime', 'virkningfra': 'DateTime', 'virkningsaktoer': 'TextEdit', 'samletfastejendomlokalid': 'TextEdit', 'skelforretningssagslokalid': 'TextEdit', 'stammerfrajordstykkelokalid': 'TextEdit', 'supplerendemaalingsaglokalid': 'TextEdit', 'arealberegningsmetode': 'TextEdit', 'arealbetegnelse': 'TextEdit', 'arealtype': 'TextEdit', 'brugsretsareal': 'CheckBox', 'delnummer': 'TextEdit', 'faelleslod': 'CheckBox', 'matrikelnummer': 'TextEdit', 'ejerlavskode': 'TextEdit', 'sognekode': 'TextEdit', 'kommunekode': 'TextEdit', 'regionskode': 'TextEdit', 'registreretareal_uom': 'TextEdit', 'registreretareal': 'TextEdit', 'vandarealinkludering': 'TextEdit', 'vejareal_uom': 'TextEdit', 'vejareal': 'TextEdit', 'vejarealberegningsstatus': 'TextEdit', 'fredskov.areal_uom': 'TextEdit', 'fredskov.areal': 'TextEdit', 'fredskov.omfang': 'TextEdit', 'jordrente.omfang': 'TextEdit', 'klitfredning.areal_uom': 'TextEdit', 'klitfredning.areal': 'TextEdit', 'klitfredning.omfang': 'TextEdit', 'majoratsskov.nummer': 'TextEdit', 'majoratsskov.omfang': 'TextEdit', 'strandbeskyttelse.omfang': 'TextEdit', 'strandbeskyttelse.areal_uom': 'TextEdit', 'strandbeskyttelse.areal': 'TextEdit', 'stormfaldsnotering': 'CheckBox', });
lyr_Jordstykker_matrikler_slagelse_v3jordstykke_gldende_5.set('fieldImages', {'fid': 'TextEdit', 'id': 'TextEdit', 'metadataproperty': 'TextEdit', 'description_href': 'TextEdit', 'description_title': 'TextEdit', 'description_nilreason': 'TextEdit', 'description': 'TextEdit', 'descriptionreference_href': 'TextEdit', 'descriptionreference_title': 'TextEdit', 'descriptionreference_nilreason': 'TextEdit', 'identifier_codespace': 'TextEdit', 'identifier': 'TextEdit', 'name': 'TextEdit', 'location_location': 'TextEdit', 'forretningshaendelse': 'TextEdit', 'senestesaglokalid': 'TextEdit', 'forretningsproces': 'TextEdit', 'id.namespace': 'TextEdit', 'id.lokalid': 'TextEdit', 'paataenkthandling': 'TextEdit', 'registreringfra': 'DateTime', 'virkningfra': 'DateTime', 'virkningsaktoer': 'TextEdit', 'samletfastejendomlokalid': 'TextEdit', 'skelforretningssagslokalid': 'TextEdit', 'stammerfrajordstykkelokalid': 'TextEdit', 'supplerendemaalingsaglokalid': 'TextEdit', 'arealberegningsmetode': 'TextEdit', 'arealbetegnelse': 'TextEdit', 'arealtype': 'TextEdit', 'brugsretsareal': 'CheckBox', 'delnummer': 'TextEdit', 'faelleslod': 'CheckBox', 'matrikelnummer': 'TextEdit', 'ejerlavskode': 'TextEdit', 'sognekode': 'TextEdit', 'kommunekode': 'TextEdit', 'regionskode': 'TextEdit', 'registreretareal_uom': 'TextEdit', 'registreretareal': 'TextEdit', 'vandarealinkludering': 'TextEdit', 'vejareal_uom': 'TextEdit', 'vejareal': 'TextEdit', 'vejarealberegningsstatus': 'TextEdit', 'fredskov.areal_uom': 'TextEdit', 'fredskov.areal': 'TextEdit', 'fredskov.omfang': 'TextEdit', 'jordrente.omfang': 'TextEdit', 'klitfredning.areal_uom': 'TextEdit', 'klitfredning.areal': 'TextEdit', 'klitfredning.omfang': 'TextEdit', 'majoratsskov.nummer': 'TextEdit', 'majoratsskov.omfang': 'TextEdit', 'strandbeskyttelse.omfang': 'TextEdit', 'strandbeskyttelse.areal_uom': 'TextEdit', 'strandbeskyttelse.areal': 'TextEdit', 'stormfaldsnotering': 'CheckBox', });
lyr_Jordstykker_matrikler_slagelse_v2jordstykke_gldende_6.set('fieldImages', {'fid': 'TextEdit', 'id': 'TextEdit', 'metadataproperty': 'TextEdit', 'description_href': 'TextEdit', 'description_title': 'TextEdit', 'description_nilreason': 'TextEdit', 'description': 'TextEdit', 'descriptionreference_href': 'TextEdit', 'descriptionreference_title': 'TextEdit', 'descriptionreference_nilreason': 'TextEdit', 'identifier_codespace': 'TextEdit', 'identifier': 'TextEdit', 'name': 'TextEdit', 'location_location': 'TextEdit', 'forretningshaendelse': 'TextEdit', 'senestesaglokalid': 'TextEdit', 'forretningsproces': 'TextEdit', 'id.namespace': 'TextEdit', 'id.lokalid': 'TextEdit', 'paataenkthandling': 'TextEdit', 'registreringfra': 'DateTime', 'virkningfra': 'DateTime', 'virkningsaktoer': 'TextEdit', 'samletfastejendomlokalid': 'TextEdit', 'skelforretningssagslokalid': 'TextEdit', 'stammerfrajordstykkelokalid': 'TextEdit', 'supplerendemaalingsaglokalid': 'TextEdit', 'arealberegningsmetode': 'TextEdit', 'arealbetegnelse': 'TextEdit', 'arealtype': 'TextEdit', 'brugsretsareal': 'CheckBox', 'delnummer': 'TextEdit', 'faelleslod': 'CheckBox', 'matrikelnummer': 'TextEdit', 'ejerlavskode': 'TextEdit', 'sognekode': 'TextEdit', 'kommunekode': 'TextEdit', 'regionskode': 'TextEdit', 'registreretareal_uom': 'TextEdit', 'registreretareal': 'TextEdit', 'vandarealinkludering': 'TextEdit', 'vejareal_uom': 'TextEdit', 'vejareal': 'TextEdit', 'vejarealberegningsstatus': 'TextEdit', 'fredskov.areal_uom': 'TextEdit', 'fredskov.areal': 'TextEdit', 'fredskov.omfang': 'TextEdit', 'jordrente.omfang': 'TextEdit', 'klitfredning.areal_uom': 'TextEdit', 'klitfredning.areal': 'TextEdit', 'klitfredning.omfang': 'TextEdit', 'majoratsskov.nummer': 'TextEdit', 'majoratsskov.omfang': 'TextEdit', 'strandbeskyttelse.omfang': 'TextEdit', 'strandbeskyttelse.areal_uom': 'TextEdit', 'strandbeskyttelse.areal': 'TextEdit', 'stormfaldsnotering': 'CheckBox', });
lyr_Jordstykker_matrikler_slagelsejordstykke_gldende_7.set('fieldImages', {'fid': 'TextEdit', 'id': 'TextEdit', 'metadataproperty': 'TextEdit', 'description_href': 'TextEdit', 'description_title': 'TextEdit', 'description_nilreason': 'TextEdit', 'description': 'TextEdit', 'descriptionreference_href': 'TextEdit', 'descriptionreference_title': 'TextEdit', 'descriptionreference_nilreason': 'TextEdit', 'identifier_codespace': 'TextEdit', 'identifier': 'TextEdit', 'name': 'TextEdit', 'location_location': 'TextEdit', 'forretningshaendelse': 'TextEdit', 'senestesaglokalid': 'TextEdit', 'forretningsproces': 'TextEdit', 'id.namespace': 'TextEdit', 'id.lokalid': 'TextEdit', 'paataenkthandling': 'TextEdit', 'registreringfra': 'DateTime', 'virkningfra': 'DateTime', 'virkningsaktoer': 'TextEdit', 'samletfastejendomlokalid': 'TextEdit', 'skelforretningssagslokalid': 'TextEdit', 'stammerfrajordstykkelokalid': 'TextEdit', 'supplerendemaalingsaglokalid': 'TextEdit', 'arealberegningsmetode': 'TextEdit', 'arealbetegnelse': 'TextEdit', 'arealtype': 'TextEdit', 'brugsretsareal': 'CheckBox', 'delnummer': 'TextEdit', 'faelleslod': 'CheckBox', 'matrikelnummer': 'TextEdit', 'ejerlavskode': 'TextEdit', 'sognekode': 'TextEdit', 'kommunekode': 'TextEdit', 'regionskode': 'TextEdit', 'registreretareal_uom': 'TextEdit', 'registreretareal': 'TextEdit', 'vandarealinkludering': 'TextEdit', 'vejareal_uom': 'TextEdit', 'vejareal': 'TextEdit', 'vejarealberegningsstatus': 'TextEdit', 'fredskov.areal_uom': 'TextEdit', 'fredskov.areal': 'TextEdit', 'fredskov.omfang': 'TextEdit', 'jordrente.omfang': 'TextEdit', 'klitfredning.areal_uom': 'TextEdit', 'klitfredning.areal': 'TextEdit', 'klitfredning.omfang': 'TextEdit', 'majoratsskov.nummer': 'TextEdit', 'majoratsskov.omfang': 'TextEdit', 'strandbeskyttelse.omfang': 'TextEdit', 'strandbeskyttelse.areal_uom': 'TextEdit', 'strandbeskyttelse.areal': 'TextEdit', 'stormfaldsnotering': 'CheckBox', });
lyr_Kortlgges_feltID_8.set('fieldImages', {'Objekt_id': 'TextEdit', 'Natyp_navn': 'TextEdit', 'StedNavn': 'TextEdit', 'Orden': 'TextEdit', 'Polygon_name': 'TextEdit', });
lyr_Kommunegrnse_slagelsekommuneinddeling_dagi_110000_1.set('fieldLabels', {'fid': 'no label', 'id': 'no label', 'metadataproperty': 'no label', 'description_href': 'no label', 'description_title': 'no label', 'description_nilreason': 'no label', 'description': 'no label', 'descriptionreference_href': 'no label', 'descriptionreference_title': 'no label', 'descriptionreference_nilreason': 'no label', 'identifier_codespace': 'no label', 'identifier': 'no label', 'name': 'no label', 'location_location': 'no label', 'id.namespace': 'no label', 'id.lokalid': 'no label', 'status': 'no label', 'geometristatus': 'no label', 'virkningfra': 'no label', 'virkningtil': 'no label', 'virkningsaktoer': 'no label', 'forretningshaendelse': 'no label', 'registreringfra': 'no label', 'registreringtil': 'no label', 'registreringsaktoer': 'no label', 'forretningsomraade': 'no label', 'forretningsproces': 'no label', 'dagiid': 'no label', 'navn': 'no label', 'redigeringsret': 'no label', 'dataspecifikation': 'no label', 'landekode': 'no label', 'skala': 'no label', 'udtraeksdato': 'no label', 'kommunekode': 'no label', 'lau1vaerdi': 'no label', 'udenforkommuneinddeling': 'no label', 'regionskode': 'no label', 'regionslokalid': 'no label', 'region_owns': 'no label', 'region_href': 'no label', 'region_title': 'no label', 'region_nilreason': 'no label', });
lyr_25mhjdekurveeksportdhm_kurve__25_m_wfs_2.set('fieldLabels', {'fid': 'no label', 'kurveId': 'no label', 'objektnavn': 'no label', 'hjaelpekurve': 'no label', 'hoejde': 'no label', });
lyr_Vandlbsmidte_slagelse_sydvandlbsmidte_3.set('fieldLabels', {'fid': 'no label', 'id': 'no label', 'metadataproperty': 'no label', 'description_href': 'no label', 'description_title': 'no label', 'description_nilreason': 'no label', 'description': 'no label', 'descriptionreference_href': 'no label', 'descriptionreference_title': 'no label', 'descriptionreference_nilreason': 'no label', 'identifier_codespace': 'no label', 'identifier': 'no label', 'name': 'no label', 'location_location': 'no label', 'id.namespace': 'no label', 'id.lokalid': 'no label', 'tempid': 'no label', 'status': 'no label', 'geometristatus': 'no label', 'registreringsspecifikation': 'no label', 'dataansvar': 'no label', 'forretningshaendelse': 'no label', 'forretningsomraade': 'no label', 'forretningsproces': 'no label', 'registreringsaktoer': 'no label', 'registreringfra': 'no label', 'registreringtil': 'no label', 'virkningsaktoer': 'no label', 'virkningfra': 'no label', 'virkningtil': 'no label', 'plannoejagtighed': 'no label', 'planstedfaestelsesmetode': 'no label', 'vertikalnoejagtighed': 'no label', 'vertikalstedfaestelsesmetode': 'no label', 'applikation': 'no label', 'kommentar': 'no label', 'vandloebstype': 'no label', 'vanduuid': 'no label', 'fraknude': 'no label', 'tilknude': 'no label', 'faldretning': 'no label', 'netvaerk': 'no label', 'midtebredde': 'no label', 'synligvandloebsmidte': 'no label', 'link': 'no label', });
lyr_Jordstykker_matrikler_slagelse_v4jordstykke_gldende_4.set('fieldLabels', {'fid': 'no label', 'id': 'no label', 'metadataproperty': 'no label', 'description_href': 'no label', 'description_title': 'no label', 'description_nilreason': 'no label', 'description': 'no label', 'descriptionreference_href': 'no label', 'descriptionreference_title': 'no label', 'descriptionreference_nilreason': 'no label', 'identifier_codespace': 'no label', 'identifier': 'no label', 'name': 'no label', 'location_location': 'no label', 'forretningshaendelse': 'no label', 'senestesaglokalid': 'no label', 'forretningsproces': 'no label', 'id.namespace': 'no label', 'id.lokalid': 'no label', 'paataenkthandling': 'no label', 'registreringfra': 'no label', 'virkningfra': 'no label', 'virkningsaktoer': 'no label', 'samletfastejendomlokalid': 'no label', 'skelforretningssagslokalid': 'no label', 'stammerfrajordstykkelokalid': 'no label', 'supplerendemaalingsaglokalid': 'no label', 'arealberegningsmetode': 'no label', 'arealbetegnelse': 'no label', 'arealtype': 'no label', 'brugsretsareal': 'no label', 'delnummer': 'no label', 'faelleslod': 'no label', 'matrikelnummer': 'no label', 'ejerlavskode': 'no label', 'sognekode': 'no label', 'kommunekode': 'no label', 'regionskode': 'no label', 'registreretareal_uom': 'no label', 'registreretareal': 'no label', 'vandarealinkludering': 'no label', 'vejareal_uom': 'no label', 'vejareal': 'no label', 'vejarealberegningsstatus': 'no label', 'fredskov.areal_uom': 'no label', 'fredskov.areal': 'no label', 'fredskov.omfang': 'no label', 'jordrente.omfang': 'no label', 'klitfredning.areal_uom': 'no label', 'klitfredning.areal': 'no label', 'klitfredning.omfang': 'no label', 'majoratsskov.nummer': 'no label', 'majoratsskov.omfang': 'no label', 'strandbeskyttelse.omfang': 'no label', 'strandbeskyttelse.areal_uom': 'no label', 'strandbeskyttelse.areal': 'no label', 'stormfaldsnotering': 'no label', });
lyr_Jordstykker_matrikler_slagelse_v3jordstykke_gldende_5.set('fieldLabels', {'fid': 'no label', 'id': 'no label', 'metadataproperty': 'no label', 'description_href': 'no label', 'description_title': 'no label', 'description_nilreason': 'no label', 'description': 'no label', 'descriptionreference_href': 'no label', 'descriptionreference_title': 'no label', 'descriptionreference_nilreason': 'no label', 'identifier_codespace': 'no label', 'identifier': 'no label', 'name': 'no label', 'location_location': 'no label', 'forretningshaendelse': 'no label', 'senestesaglokalid': 'no label', 'forretningsproces': 'no label', 'id.namespace': 'no label', 'id.lokalid': 'no label', 'paataenkthandling': 'no label', 'registreringfra': 'no label', 'virkningfra': 'no label', 'virkningsaktoer': 'no label', 'samletfastejendomlokalid': 'no label', 'skelforretningssagslokalid': 'no label', 'stammerfrajordstykkelokalid': 'no label', 'supplerendemaalingsaglokalid': 'no label', 'arealberegningsmetode': 'no label', 'arealbetegnelse': 'no label', 'arealtype': 'no label', 'brugsretsareal': 'no label', 'delnummer': 'no label', 'faelleslod': 'no label', 'matrikelnummer': 'no label', 'ejerlavskode': 'no label', 'sognekode': 'no label', 'kommunekode': 'no label', 'regionskode': 'no label', 'registreretareal_uom': 'no label', 'registreretareal': 'no label', 'vandarealinkludering': 'no label', 'vejareal_uom': 'no label', 'vejareal': 'no label', 'vejarealberegningsstatus': 'no label', 'fredskov.areal_uom': 'no label', 'fredskov.areal': 'no label', 'fredskov.omfang': 'no label', 'jordrente.omfang': 'no label', 'klitfredning.areal_uom': 'no label', 'klitfredning.areal': 'no label', 'klitfredning.omfang': 'no label', 'majoratsskov.nummer': 'no label', 'majoratsskov.omfang': 'no label', 'strandbeskyttelse.omfang': 'no label', 'strandbeskyttelse.areal_uom': 'no label', 'strandbeskyttelse.areal': 'no label', 'stormfaldsnotering': 'no label', });
lyr_Jordstykker_matrikler_slagelse_v2jordstykke_gldende_6.set('fieldLabels', {'fid': 'no label', 'id': 'no label', 'metadataproperty': 'no label', 'description_href': 'no label', 'description_title': 'no label', 'description_nilreason': 'no label', 'description': 'no label', 'descriptionreference_href': 'no label', 'descriptionreference_title': 'no label', 'descriptionreference_nilreason': 'no label', 'identifier_codespace': 'no label', 'identifier': 'no label', 'name': 'no label', 'location_location': 'no label', 'forretningshaendelse': 'no label', 'senestesaglokalid': 'no label', 'forretningsproces': 'no label', 'id.namespace': 'no label', 'id.lokalid': 'no label', 'paataenkthandling': 'no label', 'registreringfra': 'no label', 'virkningfra': 'no label', 'virkningsaktoer': 'no label', 'samletfastejendomlokalid': 'no label', 'skelforretningssagslokalid': 'no label', 'stammerfrajordstykkelokalid': 'no label', 'supplerendemaalingsaglokalid': 'no label', 'arealberegningsmetode': 'no label', 'arealbetegnelse': 'no label', 'arealtype': 'no label', 'brugsretsareal': 'no label', 'delnummer': 'no label', 'faelleslod': 'no label', 'matrikelnummer': 'no label', 'ejerlavskode': 'no label', 'sognekode': 'no label', 'kommunekode': 'no label', 'regionskode': 'no label', 'registreretareal_uom': 'no label', 'registreretareal': 'no label', 'vandarealinkludering': 'no label', 'vejareal_uom': 'no label', 'vejareal': 'no label', 'vejarealberegningsstatus': 'no label', 'fredskov.areal_uom': 'no label', 'fredskov.areal': 'no label', 'fredskov.omfang': 'no label', 'jordrente.omfang': 'no label', 'klitfredning.areal_uom': 'no label', 'klitfredning.areal': 'no label', 'klitfredning.omfang': 'no label', 'majoratsskov.nummer': 'no label', 'majoratsskov.omfang': 'no label', 'strandbeskyttelse.omfang': 'no label', 'strandbeskyttelse.areal_uom': 'no label', 'strandbeskyttelse.areal': 'no label', 'stormfaldsnotering': 'no label', });
lyr_Jordstykker_matrikler_slagelsejordstykke_gldende_7.set('fieldLabels', {'fid': 'no label', 'id': 'no label', 'metadataproperty': 'no label', 'description_href': 'no label', 'description_title': 'no label', 'description_nilreason': 'no label', 'description': 'no label', 'descriptionreference_href': 'no label', 'descriptionreference_title': 'no label', 'descriptionreference_nilreason': 'no label', 'identifier_codespace': 'no label', 'identifier': 'no label', 'name': 'no label', 'location_location': 'no label', 'forretningshaendelse': 'no label', 'senestesaglokalid': 'no label', 'forretningsproces': 'no label', 'id.namespace': 'no label', 'id.lokalid': 'no label', 'paataenkthandling': 'no label', 'registreringfra': 'no label', 'virkningfra': 'no label', 'virkningsaktoer': 'no label', 'samletfastejendomlokalid': 'no label', 'skelforretningssagslokalid': 'no label', 'stammerfrajordstykkelokalid': 'no label', 'supplerendemaalingsaglokalid': 'no label', 'arealberegningsmetode': 'no label', 'arealbetegnelse': 'no label', 'arealtype': 'no label', 'brugsretsareal': 'no label', 'delnummer': 'no label', 'faelleslod': 'no label', 'matrikelnummer': 'no label', 'ejerlavskode': 'no label', 'sognekode': 'no label', 'kommunekode': 'no label', 'regionskode': 'no label', 'registreretareal_uom': 'no label', 'registreretareal': 'no label', 'vandarealinkludering': 'no label', 'vejareal_uom': 'no label', 'vejareal': 'no label', 'vejarealberegningsstatus': 'no label', 'fredskov.areal_uom': 'no label', 'fredskov.areal': 'no label', 'fredskov.omfang': 'no label', 'jordrente.omfang': 'no label', 'klitfredning.areal_uom': 'no label', 'klitfredning.areal': 'no label', 'klitfredning.omfang': 'no label', 'majoratsskov.nummer': 'no label', 'majoratsskov.omfang': 'no label', 'strandbeskyttelse.omfang': 'no label', 'strandbeskyttelse.areal_uom': 'no label', 'strandbeskyttelse.areal': 'no label', 'stormfaldsnotering': 'no label', });
lyr_Kortlgges_feltID_8.set('fieldLabels', {'Objekt_id': 'inline label - always visible', 'Natyp_navn': 'inline label - visible with data', 'StedNavn': 'inline label - always visible', 'Orden': 'hidden field', 'Polygon_name': 'inline label - always visible', });
lyr_Kortlgges_feltID_8.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});